### ISSUE TITLE
Data preparation

### ISSUE THREAD

**Issue by Ecalpal** [SenZHANG-GitHub/ekf-imu-depth#1]
Thanks for your work!
Using IMU is very instructive for solving the scale problem of monocular depth estimation.

I think providing a detailed description of data preparation can help others better follow your research.

**Comment by SenZHANG-GitHub** [comment]
> Thanks for your work! Using IMU is very instructive for solving the scale problem of monocular depth estimation.
> 
> I think providing a detailed description of data preparation can help others better follow your research.

Hi, thanks for your suggestion. Sorry I'm quite busy currently. Will update the data preparation part next month : )

**Comment by Ecalpal** [comment]
> > Thanks for your work! Using IMU is very instructive for solving the scale problem of monocular depth estimation.
> > I think providing a detailed description of data preparation can help others better follow your research.
> 
> Hi, thanks for your suggestion. Sorry I'm quite busy currently. Will update the data preparation part next month : )

Hi! 
Since the CVPR is finished, could you update the data preparation part and release the pre-trained model?

**Comment by SenZHANG-GitHub** [comment]
> > > Thanks for your work! Using IMU is very instructive for solving the scale problem of monocular depth estimation.
> > > I think providing a detailed description of data preparation can help others better follow your research.
> > 
> > 
> > Hi, thanks for your suggestion. Sorry I'm quite busy currently. Will update the data preparation part next month : )
> 
> Hi! Since the CVPR is finished, could you update the data preparation part and release the pre-trained model?

Hi @Ecalpal  , thanks for your reminder and sorry for the delay! I have updated README.md to include detailed data preprocessing steps and the links to the pretrained models (DynaDepth R18 and R50 that use the ResNet18 and ResNet50 as the backbone, respectively).

**Comment by Ecalpal** [comment]
Wow!
Thanks for your quick response! @SenZHANG-GitHub 

Because most people who learn monocular depth estimation start from _MonoDepth_ with the synced data, re-downloading the unsynced data to run the _match_kitti_imu.py_ is time-consuming. (However, I have already started my downloading.)

With a simple code review, the project seems to lacks some .txt files, i.e., _kitti_extract/train.txt_, _kitti_extract/val.txt_, and _test_scenes.txt_.
https://github.com/SenZHANG-GitHub/ekf-imu-depth/blob/bb2118257fe68ef4e1415d166668011725ed9a4a/match_kitti_imu.py#L71-L79

**Comment by SenZHANG-GitHub** [comment]
> files

Yes the unsync files are huge. I'm transferring the matched imu files of all sequences into my laptop and uploading them into the netdisk. Since there are many files (sequences), it's a bit slow and should be ready tonight or tomorrow. I will notidy you once they are ready. 

And in case you wanna generate matched imus in the future, the txt files just contain the sequence names as in the comment (e.g.  "2011_09_30_drive_0028" ). train.txt, val.txt, and test_scene.txt contain the trainining, validation, and test sequences, respectively.

**Comment by SenZHANG-GitHub** [comment]
> Wow! Thanks for your quick response! @SenZHANG-GitHub
> 
> Because most people who learn monocular depth estimation start from _MonoDepth_ with the synced data, re-downloading the unsynced data to run the _match_kitti_imu.py_ is time-consuming. (However, I have already started my downloading.)
> 
> With a simple code review, the project seems to lacks some .txt files, i.e., _kitti_extract/train.txt_, _kitti_extract/val.txt_, and _test_scenes.txt_.
> 
> https://github.com/SenZHANG-GitHub/ekf-imu-depth/blob/bb2118257fe68ef4e1415d166668011725ed9a4a/match_kitti_imu.py#L71-L79

Yes the unsync files are huge. I'm transferring the matched imu files of all sequences into my laptop and uploading them into the netdisk. Since there are many files (sequences), it's a bit slow and should be ready tonight or tomorrow. I will notidy you once they are ready.

And in case you wanna generate matched imus in the future, the txt files just contain the sequence names as in the comment (e.g. "2011_09_30_drive_0028" ). train.txt, val.txt, and test_scene.txt contain the trainining, validation, and test sequences, respectively.

**Comment by Ecalpal** [comment]
I am looking forward to it!

Best wishes to you.

**Comment by SenZHANG-GitHub** [comment]
> I am looking forward to it!
> 
> Best wishes to you.

No problem : ) I have updated the link to our preprocessed imu files in README.md. And also be aware that we follow the practice in monodepth2 to convert the image format from png to jpg to accelerate the training process.

**Comment by Ecalpal** [comment]
Thanks for your work!

I have retrained the network and it works good!

I also find a little bug, please check the pull requests for detail.

**Comment by Ecalpal** [comment]
Thanks for your work!

I have retrained the network and it works good!

I also find a little bug, please check the pull requests for detail.

**Comment by SenZHANG-GitHub** [comment]
> Thanks for your work!
> 
> I have retrained the network and it works good!
> 
> I also find a little bug, please check the pull requests for detail.

Thanks a lot for pointing it out and the correction!
